### ISSUE TITLE
you plan to deploy this?

### ISSUE THREAD

**Issue by rohhann12** [hiteshbandhu/y-see#2]

**Comment by hiteshbandhu** [comment]
yes, sometime soon when i get the time.

**Comment by rohhann12** [comment]
you mind if i help you deploy this?
I can docerize the backend and deploy it to my azure

**Comment by hiteshbandhu** [comment]
thanks for the help man, but not now. have different plans for this one.

i'll be starting one more project, would love to share and assign you. it'd be full open source. 

meanwhile, thanks a lot
